exclude_paths:
  - "ShamsAlShamoos03.Infrastructure/Migrations/**"
  - "ShamsAlShamoos03.Client/Client/wwwroot/ThemeSite/assets/**"
  - "ShamsAlShamoos03.Client/Client/wwwroot/css/open-iconic/**"
  - "**/*.min.js"
  - "**/SweetAlert2.js"
  - "package-lock.json"
  - "**/package-lock.json"

segments:
  - name: "backend"
    path: "ShamsAlShamoos03.Server/**"
  - name: "client"
    path: "ShamsAlShamoos03.Client/**"
  - name: "shared"
    path: "ShamsAlShamoos03.Shared/**"