exclude_paths:
  - "ShamsAlShamoos03.Infrastructure/Migrations/**"
  - "ShamsAlShamoos03.Client/Client/wwwroot/ThemeSite/assets/**"
  - "ShamsAlShamoos03.Client/Client/wwwroot/css/open-iconic/**"
  - "**/*.min.js"
  - "**/SweetAlert2.js"
  - "package-lock.json"
  - "**/package-lock.json"