CREATE OR ALTER PROCEDURE dbo.Get_Monthly_Counts_ByYear
    @ShamsiDate NVARCHAR(10) -- مثال: '1403/04/01' یا '14030401'
AS
BEGIN
    SET NOCOUNT ON;
	--EXEC dbo.Get_Monthly_Counts_ByYear @ShamsiDate = '1404/04/01'

    -- حذف کاراکتر اسلش در صورت وجود
    DECLARE @Year NVARCHAR(4)
    SET @Year = LEFT(REPLACE(@ShamsiDate, '/', ''), 4)

    DECLARE @Year1 NVARCHAR(4) = CAST(CAST(@Year AS INT) - 2 AS NVARCHAR)
    DECLARE @Year2 NVARCHAR(4) = CAST(CAST(@Year AS INT) - 1 AS NVARCHAR)
    DECLARE @Year3 NVARCHAR(4) = @Year -- امسال

    SELECT
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year1 AND SUBSTRING(EMP_DAT, 5, 2) = '01' THEN 1 ELSE 0 END) AS Month_01_Year1,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year1 AND SUBSTRING(EMP_DAT, 5, 2) = '02' THEN 1 ELSE 0 END) AS Month_02_Year1,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year1 AND SUBSTRING(EMP_DAT, 5, 2) = '03' THEN 1 ELSE 0 END) AS Month_03_Year1,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year1 AND SUBSTRING(EMP_DAT, 5, 2) = '04' THEN 1 ELSE 0 END) AS Month_04_Year1,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year1 AND SUBSTRING(EMP_DAT, 5, 2) = '05' THEN 1 ELSE 0 END) AS Month_05_Year1,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year1 AND SUBSTRING(EMP_DAT, 5, 2) = '06' THEN 1 ELSE 0 END) AS Month_06_Year1,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year1 AND SUBSTRING(EMP_DAT, 5, 2) = '07' THEN 1 ELSE 0 END) AS Month_07_Year1,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year1 AND SUBSTRING(EMP_DAT, 5, 2) = '08' THEN 1 ELSE 0 END) AS Month_08_Year1,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year1 AND SUBSTRING(EMP_DAT, 5, 2) = '09' THEN 1 ELSE 0 END) AS Month_09_Year1,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year1 AND SUBSTRING(EMP_DAT, 5, 2) = '10' THEN 1 ELSE 0 END) AS Month_10_Year1,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year1 AND SUBSTRING(EMP_DAT, 5, 2) = '11' THEN 1 ELSE 0 END) AS Month_11_Year1,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year1 AND SUBSTRING(EMP_DAT, 5, 2) = '12' THEN 1 ELSE 0 END) AS Month_12_Year1,

        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year2 AND SUBSTRING(EMP_DAT, 5, 2) = '01' THEN 1 ELSE 0 END) AS Month_01_Year2,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year2 AND SUBSTRING(EMP_DAT, 5, 2) = '02' THEN 1 ELSE 0 END) AS Month_02_Year2,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year2 AND SUBSTRING(EMP_DAT, 5, 2) = '03' THEN 1 ELSE 0 END) AS Month_03_Year2,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year2 AND SUBSTRING(EMP_DAT, 5, 2) = '04' THEN 1 ELSE 0 END) AS Month_04_Year2,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year2 AND SUBSTRING(EMP_DAT, 5, 2) = '05' THEN 1 ELSE 0 END) AS Month_05_Year2,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year2 AND SUBSTRING(EMP_DAT, 5, 2) = '06' THEN 1 ELSE 0 END) AS Month_06_Year2,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year2 AND SUBSTRING(EMP_DAT, 5, 2) = '07' THEN 1 ELSE 0 END) AS Month_07_Year2,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year2 AND SUBSTRING(EMP_DAT, 5, 2) = '08' THEN 1 ELSE 0 END) AS Month_08_Year2,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year2 AND SUBSTRING(EMP_DAT, 5, 2) = '09' THEN 1 ELSE 0 END) AS Month_09_Year2,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year2 AND SUBSTRING(EMP_DAT, 5, 2) = '10' THEN 1 ELSE 0 END) AS Month_10_Year2,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year2 AND SUBSTRING(EMP_DAT, 5, 2) = '11' THEN 1 ELSE 0 END) AS Month_11_Year2,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year2 AND SUBSTRING(EMP_DAT, 5, 2) = '12' THEN 1 ELSE 0 END) AS Month_12_Year2,

        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year3 AND SUBSTRING(EMP_DAT, 5, 2) = '01' THEN 1 ELSE 0 END) AS Month_01_Year3,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year3 AND SUBSTRING(EMP_DAT, 5, 2) = '02' THEN 1 ELSE 0 END) AS Month_02_Year3,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year3 AND SUBSTRING(EMP_DAT, 5, 2) = '03' THEN 1 ELSE 0 END) AS Month_03_Year3,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year3 AND SUBSTRING(EMP_DAT, 5, 2) = '04' THEN 1 ELSE 0 END) AS Month_04_Year3,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year3 AND SUBSTRING(EMP_DAT, 5, 2) = '05' THEN 1 ELSE 0 END) AS Month_05_Year3,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year3 AND SUBSTRING(EMP_DAT, 5, 2) = '06' THEN 1 ELSE 0 END) AS Month_06_Year3,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year3 AND SUBSTRING(EMP_DAT, 5, 2) = '07' THEN 1 ELSE 0 END) AS Month_07_Year3,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year3 AND SUBSTRING(EMP_DAT, 5, 2) = '08' THEN 1 ELSE 0 END) AS Month_08_Year3,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year3 AND SUBSTRING(EMP_DAT, 5, 2) = '09' THEN 1 ELSE 0 END) AS Month_09_Year3,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year3 AND SUBSTRING(EMP_DAT, 5, 2) = '10' THEN 1 ELSE 0 END) AS Month_10_Year3,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year3 AND SUBSTRING(EMP_DAT, 5, 2) = '11' THEN 1 ELSE 0 END) AS Month_11_Year3,
        SUM(CASE WHEN LEFT(EMP_DAT, 4) = @Year3 AND SUBSTRING(EMP_DAT, 5, 2) = '12' THEN 1 ELSE 0 END) AS Month_12_Year3

    FROM [NewsDB].[dbo].[View_TblMaster]
    WHERE DrjLookupSubId IN (8, 10, 12, 13)
      AND UitID01 != 123
      AND DUS_COD IN ('90901', '91');
END
