 
 
 
  SELECT  [DailyPlanEvidenceStatAmar01Summary01ID]
      ,[MelliCode]
      ,[StatAmar01]      ,[RewardDaysCount]    
      ,[TotalVacationDaysCount]
	  	   ,([CombinedTotal]-[RewardDaysCount]) as DayUseVactionWithReward
	  	   ,[TotalVacationDaysCount]-([CombinedTotal]-[RewardDaysCount]) as RemainDaysVacationCount

      ,[strStatAmar01]
	  ,SortStatAmar01
      ,[StartDate01],PersianYear
      ,[EndDate01]
      ,[DurationDays]
      ,[HolidayDaysCount]
      ,[SumStatAmar01VNoHoliday]  
,CombinedTotal
,TotalSumStatAmar01VNoHolidayPerMelliCode
,TotalSumStatAmar01333VNoHolidayPerMelliCodeAndStatAmar

,DarajeeGheshrID
,DRJ_CODSTR01
 ,DRJ_NAMGheshr1
 ,DRJ_NAMGheshr2
 ,DRJ_COD
 ,RST_COD
 ,DRJ_NAM
      --,[DrjLookupTitle] 
      ,[FST_NAM]
      ,[LST_NAM]    ,[DrjLookupId],[EMP_NUM]
      ,[DrjLookupType]
       
	  ,    UitID01
      ,[UnitTitle]   as [strUitID01]  ,RST_NAM,DUS_COD
	   ,DUS_NAM
          ,[MaxContinuityHolidayDays]
      ,[Sortable01Id]
      ,[StatAmar01Description]
      ,[strSortStatAmar01]
      ,[EndDate]      ,[DailyPlanEvidence01ID]

  FROM  [dbo].[View_DailyPlanEvidenceStatAmar01Summary01_Tbl]
 
 
 
 
 
 
 
 
 
 
 
 
 --SELECT  [DailyPlanEvidenceStatAmar01Summary01ID]
 --     ,[MelliCode]
 --     ,[StatAmar01]
 --     ,[strStatAmar01]
 --     ,[StartDate01]
 --     ,[EndDate01]
 --     ,[DurationDays]
 --     ,[HolidayDaysCount]
 --     ,[SumStatAmar01VNoHoliday]
 --     ,[MaxContinuityHolidayDays]
 --     ,[Sortable01Id]
 --     ,[StatAmar01Description]
 --     ,[strSortStatAmar01]
 --     ,[EndDate]
 --     ,[DailyPlanEvidence01ID]
 --     ,[DrjLookupTitle] 
 --     ,[FST_NAM]
 --     ,[LST_NAM]    ,[DrjLookupId],[EMP_NUM]
 --     ,[DrjLookupType]
 --          ,[DrjSubLookupId]
 --     ,[DrjSubLookupTitle]
 --     ,[DrjSubLookupDescription]      ,[UnitCategoryGeneralId]
 --     ,[UnitTitle]      ,[RstLookupTitle]

      
 -- FROM  [dbo].[View_DailyPlanEvidenceStatAmar01Summary01_Tbl]

 

 
   --    INNER JOIN 
   -- dbo.View_TblMaster AS View_TblMaster 
   -- ON View_TblMaster.MelliCode = [DailyPlanEvidenceStatAmar01Summary01_Tbl].MelliCode

  	--LEFT OUTER JOIN
   --  --INNER JOIN 
   -- dbo.View_CategoriesGeneral_Tbl AS CatStatAmar01
   -- ON CatStatAmar01.CategoryGeneralId=[DailyPlanEvidenceStatAmar01Summary01_Tbl].StatAmar01 



  --order by [DailyPlanEvidence01ID],StartDate
    --order by [MaxContinuityHolidayDays]
	 --order by StartDate
	 where   [DailyPlanEvidence01ID]  is not NULL
	--and UitID01=24
	--and [StatAmar01] =581
	  --and  [MelliCode] ='5740003369'   
	  
	  	  --and  [MelliCode] ='5749561380'    
	  
	  --order by [StartDate]
	  	  --order by TotalSumStatAmar01VNoHolidayPerMelliCode




 
 --,[GBL_FNAM]
 --     ,[GBL_LNAM]
 --     ,[FAT_NAM]
 --     ,[INF_NUM]
 --     ,[BRT_COD]
 --     ,[BRT_DAT]
 --     ,[ValidEMP_DAT]
 --     ,[ValidBRT_COD]
 --     ,[ISS_COD]
 --     ,[ISS_DAT]
 --     ,[BLG_COD]
 --     ,[REL_COD]
 --     ,[REL_COD2]
 --     ,[SEX_COD]
 --     ,[MAR_COD]
 --     ,[WIF_QTY]
 --     ,[FAM_QTY]
 --     ,[SUN_QTY]
 --     ,[DOT_QTY]
 --     ,[MAS_COD]
 --     ,[HOM_DAT]
 --     ,[EMP_DAT]
 --     ,[TYP_EMP]
 --     ,[EMP_ORD]
 --     ,[EMP_YEG]
 --     ,[EMP_ORD2]
 --     ,[EDF_COD]
 --     ,[EMS_COD]
 --     ,[CHG_COD]
 --     ,[EDE_COD]
 --     ,[SUB_COD]
 --     ,[EDE_DAT]
 --     ,[LDOR_NEZ]
 --     ,[DUS_COD]
 --     ,[CUR_JOB]
 --     ,[HAZ_COD]
 --     ,[DRJ_CODA]
 --     ,[DRJ_STT]
 --     ,[RST_COD]
 --     ,[RST_COD2]
 --     ,[DAT_RST2]
 --     ,[ELL_RST]
 --     ,[EMP_GRH]
 --     ,[EMP_RAD]
 --     ,[COD_TAA]
 --     ,[COD_TAF]
 --     ,[COD_TAC]
 --     ,[SHO_JGH]
 --     ,[COD_GHA]
 --     ,[BND_NUM]
 --     ,[STR_NUM]
 --     ,[DRJ_CODJ]
 --     ,[DAT_ENT]
 --     ,[VAZ_ENT]
 --     ,[END_ENT]
 --     ,[VAZ_NGH]
 --     ,[OMD_YEG]
 --     ,[YEG_COD2]
 --     ,[DAT_YEG2]
 --     ,[TYP_MNT]
 --     ,[MNT_DAT]
 --     ,[YEG_COD]
 --     ,[PRE_DAT]
 --     ,[PRN_DAT]
 --     ,[CUR_ARS]
 --     ,[CUR_TAN]
 --     ,[NXT_ARS]
 --     ,[NXT_TAN]
 --     ,[FRE_QTY]
 --     ,[SAR_QTY]
 --     ,[LAD_QTY]
 --     ,[DAT_BAZ]
 --     ,[NUM_ETSH]
 --     ,[NUM_EPAY]
 --     ,[DAT_EPAY]
 --     ,[TOT_AML]
 --     ,[TOT_AML2]
 --     ,[ZAB_MAH]
 --     ,[VAZ_ESA]
 --     ,[VAZ_GRO]
 --     ,[NAZ_COD]
 --     ,[DAT_NAZ]
 --     ,[BOD_COD]
 --     ,[DRSAD_JA]
 --     ,[DRSAD_JB]
 --     ,[ADDRES]
 --     ,[COD_TEL]
 --     ,[TEL_NUM]
 --     ,[COL_EYE]
 --     ,[VAZN_PER]
 --     ,[HIG_PER]
 --     ,[SIZ_FOT]
 --     ,[SIZ_KLA]
 --     ,[OK_SAB]
 --     ,[FER_YEG]
 --     ,[RET_COD]
 --     ,[VAZ_FAR]
 --     ,[T_ENTER]
 --     ,[SW_PRT]
 --     ,[KLD_SHGL]
 --     ,[GED_OT]
 --     ,[CORS_T]
 --     ,[ROSH_P]
 --     ,[GHE_SHR]
 --     ,[COD_C1]
 --     ,[COD_C2]
 --     ,[COD_C3]
 --     ,[COD_C4]
 --     ,[COD_C12]
 --     ,[COD_C78]
 --     ,[JOB_DES]
 --     ,[DAT_ERTB]
 --     ,[DAT_ERTG]
 --     ,[TYP_GHE]
 --     ,[DAT_RAS]
 --     ,[CHG_TYP]
 --     ,[KHD_TYP]
 --     ,[SOT_DAT]
 --     ,[DAT_NGH]
 --     ,[DAT_OMD]
 --     ,[GHESHR]
 --     ,[COD4]
 --     ,[DAT_BAZS]
 --     ,[EmployArchismDuration]
 --     ,[EmployUniversityCode]
 --     ,[EmploySectionCode]
 --     ,[EmployServiceTypeCode]
 --     ,[LengthCode]
 --     ,[PeopleCode]
 --     ,[DiscountStatus]
 --     ,[CHG_TAR]
 --     ,[CHG_ENT]
 --     ,[datMedicalClassBegin]
 --     ,[datMedicalClassEnd]
 --     ,[HasChanged]
 --     ,[LastChangeTime]
 --     ,[HasYegan]
 --     ,[LastYegan]
 --     ,[YEG_COD2_Tmp]
 --     ,[HasYegan_Tmp]
 --     ,[MAK_SR]
 --     ,[DeliverTypeCode]
 --     ,[Tel_workplace]
 --     ,[Tel_mobile]
 --     ,[Postcode]
 --     ,[code_mosalsal]
 --     ,[shomareh_seri]
 --     ,[harfe_seri]
 --     ,[FstNamEN]
 --     ,[LstNamEN]
 --     ,[FlightEvidence01ID]
 --     ,[StandCheckWritten01ID]
 --     ,[HealthEvidence01ID]
 --     ,[NoNoticeEvidence01ID]
 --     ,[EnglishExamEvidence01ID]
 --     ,[PhoneEvidence01ID]
 --     ,[AdressEvidence01ID]
 --     ,[LastFlightDate]
 --     ,[TotalFlightTime]
 --     ,[TotalFlightTimeDateTime]
 --     ,[TotalFlightTimeTimeSpan]
 --     ,[TotalFlightTimeNew01]
 --     ,[DayValidFlight]
 --     ,[SUMCPHOOD]
 --     ,[SUMCPHOODNew01]
 --     ,[SUMCPN]
 --     ,[SUMCPNNew01]
 --     ,[SUMCPNY]
 --     ,[SUMCPNYNew01]
 --     ,[SUMCPd]
 --     ,[SUMCPdNew01]
 --     ,[SUMHOOD]
 --     ,[SUMHOODNew01]
 --     ,[SUMIPHOOD]
 --     ,[SUMIPHOODNew01]
 --     ,[SUMIPN]
 --     ,[SUMIPNNew01]
 --     ,[SUMIPNY]
 --     ,[SUMIPNYNew01]
 --     ,[SUMIPd]
 --     ,[SUMIPdNew01]
 --     ,[SUMPHOOD]
 --     ,[SUMPHOODNew01]
 --     ,[SUMPN]
 --     ,[SUMPNNew01]
 --     ,[SUMPNY]
 --     ,[SUMPNYNew01]
 --     ,[SUMPd]
 --     ,[SUMPdNew01]
 --     ,[SUMSIM]
 --     ,[SUMSIMNew01]
 --     ,[SUMSIPHOOD]
 --     ,[SUMSIPHOODNew01]
 --     ,[SUMSIPN]
 --     ,[SUMSIPNNew01]
 --     ,[SUMSIPNY]
 --     ,[SUMSIPNYNew01]
 --     ,[SUMSIPd]
 --     ,[SUMSIPdNew01]
 --     ,[SUMSPHOOD]
 --     ,[SUMSPHOODNew01]
 --     ,[SUMSPN]
 --     ,[SUMSPNNew01]
 --     ,[SUMSPNY]
 --     ,[SUMSPNYNew01]
 --     ,[SUMSPd]
 --     ,[SUMSPdNew01]
 --     ,[SUMTPd]
 --     ,[SUMTPdNew01]
 --     ,[SUMYN]
 --     ,[SUMYNNew01]
 --     ,[UitID01]
 --     ,[IsPersonelImage]
 --     ,[IsSignatureEn]
 --     ,[IsSignatureFa]
 --     ,[NoFolder01]
 --     ,[NoFolder02]
 --     ,[NoFolder03]
 --     ,[RateLevel]
 --     ,[TakhasosFaniKhalabanMoshtarak]
 --     ,[TypeAc]
 --     ,[Hoghog01ID]
  
 --     ,[DrjAlphabeticSort]
 --     ,[DrjCod_h]
 --     ,[DrjTitleEn]
 --     ,[DrjLookupSubId]
 --     ,[DrjLookupSortableId]
 --     ,[DrjSortableId]
 --     ,[DrjSortableDescription]


 --     ,[DrjSection_S01]
 --     ,[DrjSection_S02]
 --     ,[DrjSeed_S01]
 --     ,[DrjSeed_S02]
 --     ,[DrjSubLookupSortableId]
 --     ,[DrjSubSortableId]
 --     ,[DrjSubSortableDescription]
 --     ,[RstLookupId]
 --     ,[RstLookupType]
 --     ,[UnitDescription]
 --     ,[SubISFatmandeYeganGhesmat01]
 --     ,[SubstrISFatmandeYeganGhesmat01]
 --     ,[ISFatmandeYeganGhesmat01]
 --     ,[strISFatmandeYeganGhesmat01]
 --     ,[sort01SFatmandeYeganGhesmat01]