


SELECT   FlightEvidence01_Tbl.[FlightEvidence01ID]
    
       ,[EvidenceFlightTitle1]
      ,[DateSrartEvidenceFlightTitle]
      ,[DateEndEvidenceFlightTitle]
      ,FlightEvidence01_Tbl.[MelliCode]

	 



	  --,[PersonnelList].[EMP_NUM]
   --   ,[PersonnelList].[FST_NAM]
   --   ,[PersonnelList].[LST_NAM]
   --   ,[PersonnelList].[GBL_FNAM]
   --   ,[PersonnelList].[GBL_LNAM]
   --   ,[PersonnelList].[FAT_NAM]
   --   ,[PersonnelList].[INF_NUM]
   --   ,[PersonnelList].[BRT_COD]
   --   ,[PersonnelList].[BRT_DAT]
   --   ,[PersonnelList].[ValidBRT_COD]
   --   ,[PersonnelList].[ISS_COD]
   --   ,[PersonnelList].[ISS_DAT]
   --   ,[PersonnelList].[BLG_COD]
   --   ,[PersonnelList].[REL_COD]
   --   ,[PersonnelList].[REL_COD2]
   --   ,[PersonnelList].[SEX_COD]
   --   ,[PersonnelList].[MAR_COD]
   --   ,[PersonnelList].[WIF_QTY]
   --   ,[PersonnelList].[FAM_QTY]
   --   ,[PersonnelList].[SUN_QTY]
   --   ,[PersonnelList].[DOT_QTY]
   --   ,[PersonnelList].[MAS_COD]
   --   ,[PersonnelList].[HOM_DAT]
   --   ,[PersonnelList].[EMP_DAT]
   --   ,[PersonnelList].[ValidEMP_DAT]
   --   ,[PersonnelList].[TYP_EMP]
   --   ,[PersonnelList].[EMP_ORD]
   --   ,[PersonnelList].[EMP_YEG]
   --   ,[PersonnelList].[EMP_ORD2]
   --   ,[PersonnelList].[EDF_COD]
   --   ,[PersonnelList].[EMS_COD]
   --   ,[PersonnelList].[CHG_COD]
   --   ,[PersonnelList].[EDE_COD]
   --   ,[PersonnelList].[SUB_COD]
   --   ,[PersonnelList].[EDE_DAT]
   --   ,[PersonnelList].[LDOR_NEZ]
   --   ,[PersonnelList].[DUS_COD]
   --   ,[PersonnelList].[CUR_JOB]
   --   ,[PersonnelList].[HAZ_COD]
   --   ,[PersonnelList].[DRJ_COD]
   --   ,[PersonnelList].[DRJ_CODA]
   --   ,[PersonnelList].[DRJ_STT]
   --   ,[PersonnelList].[RST_COD]
   --   ,[PersonnelList].[RST_COD2]
   --   ,[PersonnelList].[DAT_RST2]
   --   ,[PersonnelList].[ELL_RST]
   --   ,[PersonnelList].[EMP_GRH]
   --   ,[PersonnelList].[EMP_RAD]
   --   ,[PersonnelList].[COD_TAA]
   --   ,[PersonnelList].[COD_TAF]
   --   ,[PersonnelList].[COD_TAC]
   --   ,[PersonnelList].[SHO_JGH]
   --   ,[PersonnelList].[COD_GHA]
   --   ,[PersonnelList].[BND_NUM]
   --   ,[PersonnelList].[STR_NUM]
   --   ,[PersonnelList].[DRJ_CODJ]
   --   ,[PersonnelList].[DAT_ENT]
   --   ,[PersonnelList].[VAZ_ENT]
   --   ,[PersonnelList].[END_ENT]
   --   ,[PersonnelList].[VAZ_NGH]
   --   ,[PersonnelList].[OMD_YEG]
   --   ,[PersonnelList].[YEG_COD2]
   --   ,[PersonnelList].[DAT_YEG2]
   --   ,[PersonnelList].[TYP_MNT]
   --   ,[PersonnelList].[MNT_DAT]
   --   ,[PersonnelList].[YEG_COD]
   --   ,[PersonnelList].[PRE_DAT]
   --   ,[PersonnelList].[PRN_DAT]
   --   ,[PersonnelList].[CUR_ARS]
   --   ,[PersonnelList].[CUR_TAN]
   --   ,[PersonnelList].[NXT_ARS]
   --   ,[PersonnelList].[NXT_TAN]
   --   ,[PersonnelList].[FRE_QTY]
   --   ,[PersonnelList].[SAR_QTY]
   --   ,[PersonnelList].[LAD_QTY]
   --   ,[PersonnelList].[DAT_BAZ]
   --   ,[PersonnelList].[NUM_ETSH]
   --   ,[PersonnelList].[NUM_EPAY]
   --   ,[PersonnelList].[DAT_EPAY]
   --   ,[PersonnelList].[TOT_AML]
   --   ,[PersonnelList].[TOT_AML2]
   --   ,[PersonnelList].[ZAB_MAH]
   --   ,[PersonnelList].[VAZ_ESA]
   --   ,[PersonnelList].[VAZ_GRO]
   --   ,[PersonnelList].[NAZ_COD]
   --   ,[PersonnelList].[DAT_NAZ]
   --   ,[PersonnelList].[BOD_COD]
   --   ,[PersonnelList].[DRSAD_JA]
   --   ,[PersonnelList].[DRSAD_JB]
   --   ,[PersonnelList].[ADDRES]
   --   ,[PersonnelList].[COD_TEL]
   --   ,[PersonnelList].[TEL_NUM]
   --   ,[PersonnelList].[COL_EYE]
   --   ,[PersonnelList].[VAZN_PER]
   --   ,[PersonnelList].[HIG_PER]
   --   ,[PersonnelList].[SIZ_FOT]
   --   ,[PersonnelList].[SIZ_KLA]
   --   ,[PersonnelList].[OK_SAB]
   --   ,[PersonnelList].[FER_YEG]
   --   ,[PersonnelList].[RET_COD]
   --   ,[PersonnelList].[VAZ_FAR]
   --   ,[PersonnelList].[T_ENTER]
   --   ,[PersonnelList].[SW_PRT]
   --   ,[PersonnelList].[KLD_SHGL]
   --   ,[PersonnelList].[GED_OT]
   --   ,[PersonnelList].[CORS_T]
   --   ,[PersonnelList].[ROSH_P]
   --   ,[PersonnelList].[GHE_SHR]
   --   ,[PersonnelList].[COD_C1]
   --   ,[PersonnelList].[COD_C2]
   --   ,[PersonnelList].[COD_C3]
   --   ,[PersonnelList].[COD_C4]
   --   ,[PersonnelList].[COD_C12]
   --   ,[PersonnelList].[COD_C78]
   --   ,[PersonnelList].[JOB_DES]
   --   ,[PersonnelList].[DAT_ERTB]
   --   ,[PersonnelList].[DAT_ERTG]
   --   ,[PersonnelList].[TYP_GHE]
   --   ,[PersonnelList].[DAT_RAS]
   --   ,[PersonnelList].[CHG_TYP]
   --   ,[PersonnelList].[KHD_TYP]
   --   ,[PersonnelList].[SOT_DAT]
   --   ,[PersonnelList].[DAT_NGH]
   --   ,[PersonnelList].[DAT_OMD]
   --   ,[PersonnelList].[GHESHR]
   --   ,[PersonnelList].[COD4]
   --   ,[PersonnelList].[DAT_BAZS]
   --   ,[PersonnelList].[EmployArchismDuration]
   --   ,[PersonnelList].[EmployUniversityCode]
   --   ,[PersonnelList].[EmploySectionCode]
   --   ,[PersonnelList].[EmployServiceTypeCode]
   --   ,[PersonnelList].[LengthCode]
   --   ,[PersonnelList].[PeopleCode]
   --   ,[PersonnelList].[DiscountStatus]
   --   ,[PersonnelList].[CHG_TAR]
   --   ,[PersonnelList].[CHG_ENT]
   --   ,[PersonnelList].[datMedicalClassBegin]
   --   ,[PersonnelList].[datMedicalClassEnd]
   --   ,[PersonnelList].[HasChanged]
   --   ,[PersonnelList].[LastChangeTime]
   --   ,[PersonnelList].[HasYegan]
   --   ,[PersonnelList].[LastYegan]
   --   ,[PersonnelList].[YEG_COD2_Tmp]
   --   ,[PersonnelList].[HasYegan_Tmp]
   --   ,[PersonnelList].[MAK_SR]
   --   ,[PersonnelList].[DeliverTypeCode]
   --   ,[PersonnelList].[Tel_workplace]
   --   ,[PersonnelList].[Tel_mobile]
   --   ,[PersonnelList].[Postcode]
   --   ,[PersonnelList].[code_mosalsal]
   --   ,[PersonnelList].[shomareh_seri]
   --   ,[PersonnelList].[harfe_seri]
   --   ,[PersonnelList].[FstNamEN]
   --   ,[PersonnelList].[LstNamEN]
   --   --,[PersonnelList].[FlightEvidence01ID] as [aFlightEvidence01ID]
   --   ,[PersonnelList].[StandCheckWritten01ID]
   --   ,[PersonnelList].[HealthEvidence01ID]
   --   ,[PersonnelList].[NoNoticeEvidence01ID]
   --   ,[PersonnelList].[EnglishExamEvidence01ID]
   --   ,[PersonnelList].[PhoneEvidence01ID]
   --   ,[PersonnelList].[AdressEvidence01ID]
   --   ,[PersonnelList].[LastFlightDate]
   --   ,[PersonnelList].[TotalFlightTime]
   --   ,[PersonnelList].[TotalFlightTimeDateTime]
   --   ,[PersonnelList].[TotalFlightTimeTimeSpan]
   --   ,[PersonnelList].[TotalFlightTimeNew01]
   --   ,[PersonnelList].[DayValidFlight]
   --   ,[PersonnelList].[SUMCPHOOD]
   --   ,[PersonnelList].[SUMCPHOODNew01]
   --   ,[PersonnelList].[SUMCPN]
   --   ,[PersonnelList].[SUMCPNNew01]
   --   ,[PersonnelList].[SUMCPNY]
   --   ,[PersonnelList].[SUMCPNYNew01]
   --   ,[PersonnelList].[SUMCPd]
   --   ,[PersonnelList].[SUMCPdNew01]
   --   ,[PersonnelList].[SUMHOOD]
   --   ,[PersonnelList].[SUMHOODNew01]
   --   ,[PersonnelList].[SUMIPHOOD]
   --   ,[PersonnelList].[SUMIPHOODNew01]
   --   ,[PersonnelList].[SUMIPN]
   --   ,[PersonnelList].[SUMIPNNew01]
   --   ,[PersonnelList].[SUMIPNY]
   --   ,[PersonnelList].[SUMIPNYNew01]
   --   ,[PersonnelList].[SUMIPd]
   --   ,[PersonnelList].[SUMIPdNew01]
   --   ,[PersonnelList].[SUMPHOOD]
   --   ,[PersonnelList].[SUMPHOODNew01]
   --   ,[PersonnelList].[SUMPN]
   --   ,[PersonnelList].[SUMPNNew01]
   --   ,[PersonnelList].[SUMPNY]
   --   ,[PersonnelList].[SUMPNYNew01]
   --   ,[PersonnelList].[SUMPd]
   --   ,[PersonnelList].[SUMPdNew01]
   --   ,[PersonnelList].[SUMSIM]
   --   ,[PersonnelList].[SUMSIMNew01]
   --   ,[PersonnelList].[SUMSIPHOOD]
   --   ,[PersonnelList].[SUMSIPHOODNew01]
   --   ,[PersonnelList].[SUMSIPN]
   --   ,[PersonnelList].[SUMSIPNNew01]
   --   ,[PersonnelList].[SUMSIPNY]
   --   ,[PersonnelList].[SUMSIPNYNew01]
   --   ,[PersonnelList].[SUMSIPd]
   --   ,[PersonnelList].[SUMSIPdNew01]
   --   ,[PersonnelList].[SUMSPHOOD]
   --   ,[PersonnelList].[SUMSPHOODNew01]
   --   ,[PersonnelList].[SUMSPN]
   --   ,[PersonnelList].[SUMSPNNew01]
   --   ,[PersonnelList].[SUMSPNY]
   --   ,[PersonnelList].[SUMSPNYNew01]
   --   ,[PersonnelList].[SUMSPd]
   --   ,[PersonnelList].[SUMSPdNew01]
   --   ,[PersonnelList].[SUMTPd]
   --   ,[PersonnelList].[SUMTPdNew01]
   --   ,[PersonnelList].[SUMYN]
   --   ,[PersonnelList].[SUMYNNew01]
   --   ,[PersonnelList].[UitID01]
   --   ,[PersonnelList].[IsPersonelImage]
   --   ,[PersonnelList].[IsSignatureEn]
   --   ,[PersonnelList].[IsSignatureFa]
   --   ,[PersonnelList].[UitIDGaurd01]
   --   ,[PersonnelList].[NoFolder01]
   --   ,[PersonnelList].[NoFolder02]
   --   ,[PersonnelList].[NoFolder03]
   --   ,[PersonnelList].[RateLevel]
   --   ,[PersonnelList].[TakhasosFaniKhalabanMoshtarak]
   --   ,[PersonnelList].[TypeAc]
   --   ,[PersonnelList].[Hoghog01ID]
   --   ,[PersonnelList].[ISFatmandeYeganGhesmat01]
   --   ,[PersonnelList].[DrjLookupId]
   --   ,[PersonnelList].[DrjLookupType]
   --   ,[PersonnelList].[DrjLookupTitle]
   --   ,[PersonnelList].[DrjAlphabeticSort]
   --   ,[PersonnelList].[DrjCod_h]
   --   ,[PersonnelList].[DrjTitleEn]
   --   ,[PersonnelList].[DrjLookupSubId]
   --   ,[PersonnelList].[DrjLookupSortableId]
   --   ,[PersonnelList].[DrjSortableId]
   --   ,[PersonnelList].[DrjSortableDescription]
   --   ,[PersonnelList].[DrjSubLookupId]
   --   ,[PersonnelList].[DrjSubLookupTitle]
   --   ,[PersonnelList].[DrjSubLookupDescription]
   --   ,[PersonnelList].[DrjSection_S01]
   --   ,[PersonnelList].[DrjSection_S02]
   --   ,[PersonnelList].[DrjSeed_S01]
   --   ,[PersonnelList].[DrjSeed_S02]
   --   ,[PersonnelList].[DrjSubLookupSortableId]
   --   ,[PersonnelList].[DrjSubSortableId]
   --   ,[PersonnelList].[DrjSubSortableDescription]
   --   ,[PersonnelList].[RstLookupId]
   --   ,[PersonnelList].[RstLookupType]
   --   ,[PersonnelList].[RstLookupTitle]
   --   ,[PersonnelList].[CategoryGeneralId]
   --   ,[PersonnelList].[strISFatmandeYeganGhesmat01]
   --   ,[PersonnelList].[CategoryDescription]
   --   ,[PersonnelList].[SubISFatmandeYeganGhesmat01]
   --   ,[PersonnelList].[CategoryIsActive]
   --   ,[PersonnelList].[sort01SFatmandeYeganGhesmat01]
   --   ,[PersonnelList].[ooCategoryGeneralSubId]
   --   ,[PersonnelList].[SubCategoryId]
   --   ,[PersonnelList].[SubstrISFatmandeYeganGhesmat01]
   --   ,[PersonnelList].[SubCategoryDescription]
   --   ,[PersonnelList].[SubCategoryIsActive]
   --   ,[PersonnelList].[SubCategorySortableId]
   --   ,[PersonnelList].[OOSubCategoryId]
   --   ,[PersonnelList].[OOSubCategoryTitle]
   --   ,[PersonnelList].[OOSubCategoryDescription]
   --   ,[PersonnelList].[OOSubCategoryIsActive]
   --   ,[PersonnelList].[OOSubCategorySortableId]
   --   ,[PersonnelList].[MainSortableId]
   --   ,[PersonnelList].[MainSortableDescription]
   --   ,[PersonnelList].[SubSortableId]
   --   ,[PersonnelList].[SubSortableDescription]
   --   ,[PersonnelList].[UnitCategoryGeneralId]
   --   ,[PersonnelList].[UnitTitle]
   --   ,[PersonnelList].[UnitDescription]




























	     ,Sortable01_Tbl.Idsort AS SortableIdFlightEvidence01ID
    ,Sortable01_Tbl.Description AS SortableDescriptionFlightEvidence01ID

 	  ,[Rate] as [Rate]
      ,[RateEvidence01_Tbl].[Title] as [RateTitle]
      ,[RateEvidence01_Tbl].[CategoryDescription] as [RateCategoryDescription]
      ,[RateEvidence01_Tbl].[CategoryGeneralSubId] as [RateCategoryGeneralSubId]
      ,[RateEvidence01_Tbl].[CategoryIsActive] as [RateCategoryIsActive]
      ,[RateEvidence01_Tbl].[CategorySortableId] as [RateCategorySortableId]
      ,[RateEvidence01_Tbl].[ooCategoryGeneralSubId] as [RateooCategoryGeneralSubId]
      ,[RateEvidence01_Tbl].[SubCategoryId] as [RateSubCategoryId]
      ,[RateEvidence01_Tbl].[SubCategoryTitle] as [RateSubCategoryTitle]
      ,[RateEvidence01_Tbl].[SubCategoryDescription] as [RateSubCategoryDescription]
      ,[RateEvidence01_Tbl].[SubCategoryIsActive] as [RateSubCategoryIsActive] 
      ,[RateEvidence01_Tbl].[SubCategorySortableId] as [RateSubCategorySortableId]
      ,[RateEvidence01_Tbl].[OOSubCategoryId] as [RateOOSubCategoryId]
      ,[RateEvidence01_Tbl].[OOSubCategoryTitle] as [RateOOSubCategoryTitle]
      ,[RateEvidence01_Tbl].[OOSubCategoryDescription] as [RateOOSubCategoryDescription]
      ,[RateEvidence01_Tbl].[OOSubCategoryIsActive] as [RateOOSubCategoryIsActive]
      ,[RateEvidence01_Tbl].[OOSubCategorySortableId] as [RateOOSubCategorySortableId]
      ,[RateEvidence01_Tbl].[MainSortableId] as [RateMainSortableId]
      ,[RateEvidence01_Tbl].[MainSortableDescription] as [RateMainSortableDescription]
      ,[RateEvidence01_Tbl].[SubSortableId] as [RateSubSortableId]
      ,[RateEvidence01_Tbl].[SubSortableDescription] as [RateSubSortableDescription]

	  ,FlightEvidence01_Tbl.[TypeAC] as [RTypeAC]
      ,[TypeACEvidence01_Tbl].[Title] as [RTypeACTitle]
      ,[TypeACEvidence01_Tbl].[CategoryDescription] as [TypeACCategoryDescription]
      ,[TypeACEvidence01_Tbl].[CategoryGeneralSubId] as [TypeACCategoryGeneralSubId]
      ,[TypeACEvidence01_Tbl].[CategoryIsActive] as [TypeACCategoryIsActive]
      ,[TypeACEvidence01_Tbl].[CategorySortableId] as [TypeACCategorySortableId]
      ,[TypeACEvidence01_Tbl].[ooCategoryGeneralSubId] as [TypeACooCategoryGeneralSubId]
      ,[TypeACEvidence01_Tbl].[SubCategoryId] as [TypeACSubCategoryId]
      ,[TypeACEvidence01_Tbl].[SubCategoryTitle] as [TypeACSubCategoryTitle]
      ,[TypeACEvidence01_Tbl].[SubCategoryDescription] as [TypeACSubCategoryDescription]
      ,[TypeACEvidence01_Tbl].[SubCategoryIsActive] as [TypeACSubCategoryIsActive] 
      ,[TypeACEvidence01_Tbl].[SubCategorySortableId] as [TypeACSubCategorySortableId]
      ,[TypeACEvidence01_Tbl].[OOSubCategoryId] as [TypeACOOSubCategoryId]
      ,[TypeACEvidence01_Tbl].[OOSubCategoryTitle] as [TypeACOOSubCategoryTitle]
      ,[TypeACEvidence01_Tbl].[OOSubCategoryDescription] as [TypeACOOSubCategoryDescription]
      ,[TypeACEvidence01_Tbl].[OOSubCategoryIsActive] as [TypeACOOSubCategoryIsActive]
      ,[TypeACEvidence01_Tbl].[OOSubCategorySortableId] as [TypeACOOSubCategorySortableId]
      ,[TypeACEvidence01_Tbl].[MainSortableId] as [TypeACMainSortableId]
      ,[TypeACEvidence01_Tbl].[MainSortableDescription] as [TypeACMainSortableDescription]
      ,[TypeACEvidence01_Tbl].[SubSortableId] as [TypeACSubSortableId]
      ,[TypeACEvidence01_Tbl].[SubSortableDescription] as [TypeACSubSortableDescription]


	  ,[EvidenceFlightTitle] as [EvidenceFlightTitle]
      ,[EvidenceFlightTitleEvidence01_Tbl].[Title] as [EvidenceFlightTitleTitle]
      ,[EvidenceFlightTitleEvidence01_Tbl].[CategoryDescription] as [EvidenceFlightTitleCategoryDescription]
      ,[EvidenceFlightTitleEvidence01_Tbl].[CategoryGeneralSubId] as [EvidenceFlightTitleCategoryGeneralSubId]
      ,[EvidenceFlightTitleEvidence01_Tbl].[CategoryIsActive] as [EvidenceFlightTitleCategoryIsActive]
      ,[EvidenceFlightTitleEvidence01_Tbl].[CategorySortableId] as [EvidenceFlightTitleCategorySortableId]
      ,[EvidenceFlightTitleEvidence01_Tbl].[ooCategoryGeneralSubId] as [EvidenceFlightTitleooCategoryGeneralSubId]
      ,[EvidenceFlightTitleEvidence01_Tbl].[SubCategoryId] as [EvidenceFlightTitleSubCategoryId]
      ,[EvidenceFlightTitleEvidence01_Tbl].[SubCategoryTitle] as [EvidenceFlightTitleSubCategoryTitle]
      ,[EvidenceFlightTitleEvidence01_Tbl].[SubCategoryDescription] as [EvidenceFlightTitleSubCategoryDescription]
      ,[EvidenceFlightTitleEvidence01_Tbl].[SubCategoryIsActive] as [EvidenceFlightTitleSubCategoryIsActive] 
      ,[EvidenceFlightTitleEvidence01_Tbl].[SubCategorySortableId] as [EvidenceFlightTitleSubCategorySortableId]
      ,[EvidenceFlightTitleEvidence01_Tbl].[OOSubCategoryId] as [EvidenceFlightTitleOOSubCategoryId]
      ,[EvidenceFlightTitleEvidence01_Tbl].[OOSubCategoryTitle] as [EvidenceFlightTitleOOSubCategoryTitle]
      ,[EvidenceFlightTitleEvidence01_Tbl].[OOSubCategoryDescription] as [EvidenceFlightTitleOOSubCategoryDescription]
      ,[EvidenceFlightTitleEvidence01_Tbl].[OOSubCategoryIsActive] as [EvidenceFlightTitleOOSubCategoryIsActive]
      ,[EvidenceFlightTitleEvidence01_Tbl].[OOSubCategorySortableId] as [EvidenceFlightTitleOOSubCategorySortableId]
      ,[EvidenceFlightTitleEvidence01_Tbl].[MainSortableId] as [EvidenceFlightTitleMainSortableId]
      ,[EvidenceFlightTitleEvidence01_Tbl].[MainSortableDescription] as [EvidenceFlightTitleMainSortableDescription]
      ,[EvidenceFlightTitleEvidence01_Tbl].[SubSortableId] as [EvidenceFlightTitleSubSortableId]
      ,[EvidenceFlightTitleEvidence01_Tbl].[SubSortableDescription] as [EvidenceFlightTitleSubSortableDescription]


	        ,[FlightEvidence01_Tbl].[IsHaveJob]
	  	         ,  CASE 
                WHEN [FlightEvidence01_Tbl].[IsHaveJob] IN (0) THEN COALESCE( N'غیر فعال', '''')
                WHEN [FlightEvidence01_Tbl].[IsHaveJob] IN (1) THEN COALESCE( N'فعال', '''')
                ELSE '0'
				END AS IsHaveJobstring





  FROM  [dbo].[FlightEvidence01_Tbl]




 LEFT JOIN 
    dbo.View_CategoriesGeneral_Tbl as RateEvidence01_Tbl 
    ON RateEvidence01_Tbl.CategoryGeneralId = FlightEvidence01_Tbl.Rate 

 LEFT JOIN 
    dbo.View_CategoriesGeneral_Tbl as TypeACEvidence01_Tbl 
    ON TypeACEvidence01_Tbl.CategoryGeneralId = FlightEvidence01_Tbl.[TypeAC] 
 
 LEFT JOIN 
    dbo.View_CategoriesGeneral_Tbl as EvidenceFlightTitleEvidence01_Tbl 
    ON EvidenceFlightTitleEvidence01_Tbl.CategoryGeneralId = FlightEvidence01_Tbl.[EvidenceFlightTitle] 

 
 LEFT OUTER JOIN 
    dbo.Sortable01_Tbl Sortable01_Tbl 
    ON FlightEvidence01_Tbl.Sortable01Id = Sortable01_Tbl.Sortable01Id

	   --  INNER JOIN 
    --dbo.View_TblMaster AS PersonnelList 
    --ON FlightEvidence01_Tbl.MelliCode = PersonnelList.MelliCode

