
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShamsAlShamoos03.Shared.Models
{
    public class Daily1352INSPNextDuePlanEvidence01ViewModelcat
    {
        public string? Daily1352INSPNextDuePlanEvidence01ID { get; set; }
        public string? Daily1352INSPPlanEvidence01ID { get; set; }
        public string? JobStart01 { get; set; }
        public string? JobEnd01 { get; set; }
        public string? NextDue { get; set; }
        public int? Sortable01Id { get; set; }

 
        public string? RegisterPesronel01 { get; set; }
        public string? EditedPesronel01 { get; set; }
         public string? NOTAMCHECKETitle01 { get; set; }
        public string? NOTAMCHECKETitle02 { get; set; }
        public string? NOTAMCHECKETitle03 { get; set; }
        public string? TimeSignatureOREditYagen01 { get; set; }
        public bool IsHaveJob { get; set; }
        public string? Daily1352INSPPlanEvidence01IDINSPPlan { get; set; }

         public string? RegisterPesronel01INSPPlan { get; set; }
        public string? RegisterPesronel01strJobTitleINSPPlan { get; set; }
        public string? RegisterPesronel01strJobTitleNINSPPlan { get; set; }
        public string? RegisterPesronel01strINSPPlan { get; set; }
        public string? RegisterPesronel01strMelicodeINSPPlan { get; set; }
        public string? RegisterPesronel01strDarajeeINSPPlan { get; set; }
        public string? RegisterPesronel01strFirstNameINSPPlan { get; set; }
        public string? RegisterPesronel01strLastNameINSPPlan { get; set; }
        public string? RegisterPesronel01strEMP_NUMINSPPlan { get; set; }
        public string? EditedPesronel01INSPPlan { get; set; }
        public string? EditedPesronel01strJobTitleINSPPlan { get; set; }
        public string? EditedPesronel01strJobTitleNINSPPlan { get; set; }
        public string? EditedPesronel01strINSPPlan { get; set; }
        public string? EditedPesronel01strMelicodeINSPPlan { get; set; }
        public string? EditedPesronel01strDarajeeINSPPlan { get; set; }
        public string? EditedPesronel01strFirstNameINSPPlan { get; set; }
        public string? EditedPesronel01strLastNameINSPPlan { get; set; }
        public string? EditedPesronel01strEMP_NUMINSPPlan { get; set; }
        public int? Sortable01IdINSPPlan { get; set; }
        public string? NOTAMCHECKETitle01INSPPlan { get; set; }
        public string? NOTAMCHECKETitle02INSPPlan { get; set; }
        public string? NOTAMCHECKETitle03INSPPlan { get; set; }
        public string? TimeSignatureOREditYagen01INSPPlan { get; set; }
        public string? IsHaveJobINSPPlan { get; set; }
        public string? IsHaveJobString01INSPPlan { get; set; }
        public string? HelicopterTailEvidence01INSPPlan { get; set; }
        public int? AIRCRAFTSortable01IdINSPPlan { get; set; }
        public string? StatusHelicopterTailEvidence01INSPPlan { get; set; }
        public string? TitleStatusINSPPlan { get; set; }
        public string? CategoryDescriptionStatusINSPPlan { get; set; }
        public string? CategoryGeneralSubIdStatusINSPPlan { get; set; }
        public string? CategoryIsActiveStatusINSPPlan { get; set; }
        public string? CategorySortableIdStatusINSPPlan { get; set; }
        public string? ooCategoryGeneralSubIdStatusINSPPlan { get; set; }
        public string? SubCategoryIdStatusINSPPlan { get; set; }
        public string? SubCategoryTitleStatusINSPPlan { get; set; }
        public string? SubCategoryDescriptionStatusINSPPlan { get; set; }
        public string? SubCategoryIsActiveStatusINSPPlan { get; set; }
        public string? SubCategorySortableIdStatusINSPPlan { get; set; }
        public string? OOSubCategoryIdStatusINSPPlan { get; set; }
        public string? OOSubCategoryTitleStatusINSPPlan { get; set; }
        public string? OOSubCategoryDescriptionStatusINSPPlan { get; set; }
        public string? OOSubCategoryIsActiveStatusINSPPlan { get; set; }
        public string? OOSubCategorySortableIdStatusINSPPlan { get; set; }
        public string? MainSortableIdStatusINSPPlan { get; set; }
        public string? MainSortableDescriptionStatusINSPPlan { get; set; }
        public string? SubSortableIdStatusINSPPlan { get; set; }
        public string? SubSortableDescriptionStatusINSPPlan { get; set; }
        public string? AIRCRAFTIsHaveJobINSPPlan { get; set; }
        public string? SeriakHelicopterINSPPlan { get; set; }
        public string? TailHelicopterINSPPlan { get; set; }
        public int?  TypeHelicopterINSPPlan { get; set; }
        public string? TitleTypeHelicopterINSPPlan { get; set; }
        public string? CategoryDescriptionTypeHelicopterINSPPlan { get; set; }
        public string? CategoryGeneralSubIdTypeHelicopterINSPPlan { get; set; }
        public string? CategoryIsActiveTypeHelicopterINSPPlan { get; set; }
        public string? CategorySortableIdTypeHelicopterINSPPlan { get; set; }
        public string? ooCategoryGeneralSubIdTypeHelicopterINSPPlan { get; set; }
        public string? SubCategoryIdTypeHelicopterINSPPlan { get; set; }
        public string? SubCategoryTitleTypeHelicopterINSPPlan { get; set; }
        public string? SubCategoryDescriptionTypeHelicopterINSPPlan { get; set; }
        public string? SubCategoryIsActiveTypeHelicopterINSPPlan { get; set; }
        public string? SubCategorySortableIdTypeHelicopterINSPPlan { get; set; }
        public string? OOSubCategoryIdTypeHelicopterINSPPlan { get; set; }
        public string? OOSubCategoryTitleTypeHelicopterINSPPlan { get; set; }
        public string? OOSubCategoryDescriptionTypeHelicopterINSPPlan { get; set; }
        public string? OOSubCategoryIsActiveTypeHelicopterINSPPlan { get; set; }
        public string? OOSubCategorySortableIdTypeHelicopterINSPPlan { get; set; }
        public string? MainSortableIdTypeHelicopterINSPPlan { get; set; }
        public string? MainSortableDescriptionTypeHelicopterINSPPlan { get; set; }
        public string? SubSortableIdTypeHelicopterINSPPlan { get; set; }
        public string? SubSortableDescriptionTypeHelicopterINSPPlan { get; set; }
        public string? AIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? TitleAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? CategoryDescriptionAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? CategoryGeneralSubIdAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? CategoryIsActiveAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? CategorySortableIdAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? ooCategoryGeneralSubIdAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? SubCategoryIdAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? SubCategoryTitleAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? SubCategoryDescriptionAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? SubCategoryIsActiveAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? SubCategorySortableIdAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? OOSubCategoryIdAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? OOSubCategoryTitleAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? OOSubCategoryDescriptionAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? OOSubCategoryIsActiveAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? OOSubCategorySortableIdAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? MainSortableIdAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? MainSortableDescriptionAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? SubSortableIdAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? SubSortableDescriptionAIRCRAFTCOLOURANDMARKINGSINSPPlan { get; set; }
        public string? CRUISINGSPEEDINSPPlan { get; set; }
        public string? TitleCRUISINGSPEEDINSPPlan { get; set; }
        public string? CategoryDescriptionCRUISINGSPEEDINSPPlan { get; set; }
        public string? CategoryGeneralSubIdCRUISINGSPEEDINSPPlan { get; set; }
        public string? CategoryIsActiveCRUISINGSPEEDINSPPlan { get; set; }
        public string? CategorySortableIdCRUISINGSPEEDINSPPlan { get; set; }
        public string? ooCategoryGeneralSubIdCRUISINGSPEEDINSPPlan { get; set; }
        public string? SubCategoryIdCRUISINGSPEEDINSPPlan { get; set; }
        public string? SubCategoryTitleCRUISINGSPEEDINSPPlan { get; set; }
        public string? SubCategoryDescriptionCRUISINGSPEEDINSPPlan { get; set; }
        public string? SubCategoryIsActiveCRUISINGSPEEDINSPPlan { get; set; }
        public string? SubCategorySortableIdCRUISINGSPEEDINSPPlan { get; set; }
        public string? OOSubCategoryIdCRUISINGSPEEDINSPPlan { get; set; }
        public string? OOSubCategoryTitleCRUISINGSPEEDINSPPlan { get; set; }
        public string? OOSubCategoryDescriptionCRUISINGSPEEDINSPPlan { get; set; }
        public string? OOSubCategoryIsActiveCRUISINGSPEEDINSPPlan { get; set; }
        public string? OOSubCategorySortableIdCRUISINGSPEEDINSPPlan { get; set; }
        public string? MainSortableIdCRUISINGSPEEDINSPPlan { get; set; }
        public string? MainSortableDescriptionCRUISINGSPEEDINSPPlan { get; set; }
        public string? SubSortableIdCRUISINGSPEEDINSPPlan { get; set; }
        public string? SubSortableDescriptionCRUISINGSPEEDINSPPlan { get; set; }
        public string? EMERGENCYRADIOINSPPlan { get; set; }
        public string? TitleEMERGENCYRADIOINSPPlan { get; set; }
        public string? CategoryDescriptionEMERGENCYRADIOINSPPlan { get; set; }
        public string? CategoryGeneralSubIdEMERGENCYRADIOINSPPlan { get; set; }
        public string? CategoryIsActiveEMERGENCYRADIOINSPPlan { get; set; }
        public string? CategorySortableIdEMERGENCYRADIOINSPPlan { get; set; }
        public string? ooCategoryGeneralSubIdEMERGENCYRADIOINSPPlan { get; set; }
        public string? SubCategoryIdEMERGENCYRADIOINSPPlan { get; set; }
        public string? SubCategoryTitleEMERGENCYRADIOINSPPlan { get; set; }
        public string? SubCategoryDescriptionEMERGENCYRADIOINSPPlan { get; set; }
        public string? SubCategoryIsActiveEMERGENCYRADIOINSPPlan { get; set; }
        public string? SubCategorySortableIdEMERGENCYRADIOINSPPlan { get; set; }
        public string? OOSubCategoryIdEMERGENCYRADIOINSPPlan { get; set; }
        public string? OOSubCategoryTitleEMERGENCYRADIOINSPPlan { get; set; }
        public string? OOSubCategoryDescriptionEMERGENCYRADIOINSPPlan { get; set; }
        public string? OOSubCategoryIsActiveEMERGENCYRADIOINSPPlan { get; set; }
        public string? OOSubCategorySortableIdEMERGENCYRADIOINSPPlan { get; set; }
        public string? MainSortableIdEMERGENCYRADIOINSPPlan { get; set; }
        public string? MainSortableDescriptionEMERGENCYRADIOINSPPlan { get; set; }
        public string? SubSortableIdEMERGENCYRADIOINSPPlan { get; set; }
        public string? SubSortableDescriptionEMERGENCYRADIOINSPPlan { get; set; }
        public string? ENDURANCEHRMININSPPlan { get; set; }
        public string? TitleENDURANCEHRMININSPPlan { get; set; }
        public string? CategoryDescriptionENDURANCEHRMININSPPlan { get; set; }
        public string? CategoryGeneralSubIdENDURANCEHRMININSPPlan { get; set; }
        public string? CategoryIsActiveENDURANCEHRMININSPPlan { get; set; }
        public string? CategorySortableIdENDURANCEHRMININSPPlan { get; set; }
        public string? ooCategoryGeneralSubIdENDURANCEHRMININSPPlan { get; set; }
        public string? SubCategoryIdENDURANCEHRMININSPPlan { get; set; }
        public string? SubCategoryTitleENDURANCEHRMININSPPlan { get; set; }
        public string? SubCategoryDescriptionENDURANCEHRMININSPPlan { get; set; }
        public string? SubCategoryIsActiveENDURANCEHRMININSPPlan { get; set; }
        public string? SubCategorySortableIdENDURANCEHRMININSPPlan { get; set; }
        public string? OOSubCategoryIdENDURANCEHRMININSPPlan { get; set; }
        public string? OOSubCategoryTitleENDURANCEHRMININSPPlan { get; set; }
        public string? OOSubCategoryDescriptionENDURANCEHRMININSPPlan { get; set; }
        public string? OOSubCategoryIsActiveENDURANCEHRMININSPPlan { get; set; }
        public string? OOSubCategorySortableIdENDURANCEHRMININSPPlan { get; set; }
        public string? MainSortableIdENDURANCEHRMININSPPlan { get; set; }
        public string? MainSortableDescriptionENDURANCEHRMININSPPlan { get; set; }
        public string? SubSortableIdENDURANCEHRMININSPPlan { get; set; }
        public string? SubSortableDescriptionENDURANCEHRMININSPPlan { get; set; }
        public string? EQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? TitleEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? CategoryDescriptionEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? CategoryGeneralSubIdEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? CategoryIsActiveEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? CategorySortableIdEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? ooCategoryGeneralSubIdEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? SubCategoryIdEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? SubCategoryTitleEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? SubCategoryDescriptionEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? SubCategoryIsActiveEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? SubCategorySortableIdEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? OOSubCategoryIdEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? OOSubCategoryTitleEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? OOSubCategoryDescriptionEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? OOSubCategoryIsActiveEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? OOSubCategorySortableIdEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? MainSortableIdEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? MainSortableDescriptionEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? SubSortableIdEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? SubSortableDescriptionEQUIPMENTANDCAPABILITIESINSPPlan { get; set; }
        public string? FLIGHTROLESINSPPlan { get; set; }
        public string? TitleFLIGHTROLESINSPPlan { get; set; }
        public string? CategoryDescriptionFLIGHTROLESINSPPlan { get; set; }
        public string? CategoryGeneralSubIdFLIGHTROLESINSPPlan { get; set; }
        public string? CategoryIsActiveFLIGHTROLESINSPPlan { get; set; }
        public string? CategorySortableIdFLIGHTROLESINSPPlan { get; set; }
        public string? ooCategoryGeneralSubIdFLIGHTROLESINSPPlan { get; set; }
        public string? SubCategoryIdFLIGHTROLESINSPPlan { get; set; }
        public string? SubCategoryTitleFLIGHTROLESINSPPlan { get; set; }
        public string? SubCategoryDescriptionFLIGHTROLESINSPPlan { get; set; }
        public string? SubCategoryIsActiveFLIGHTROLESINSPPlan { get; set; }
        public string? SubCategorySortableIdFLIGHTROLESINSPPlan { get; set; }
        public string? OOSubCategoryIdFLIGHTROLESINSPPlan { get; set; }
        public string? OOSubCategoryTitleFLIGHTROLESINSPPlan { get; set; }
        public string? OOSubCategoryDescriptionFLIGHTROLESINSPPlan { get; set; }
        public string? OOSubCategoryIsActiveFLIGHTROLESINSPPlan { get; set; }
        public string? OOSubCategorySortableIdFLIGHTROLESINSPPlan { get; set; }
        public string? MainSortableIdFLIGHTROLESINSPPlan { get; set; }
        public string? MainSortableDescriptionFLIGHTROLESINSPPlan { get; set; }
        public string? SubSortableIdFLIGHTROLESINSPPlan { get; set; }
        public string? SubSortableDescriptionFLIGHTROLESINSPPlan { get; set; }
        public string? TYPEOFFLIGHTINSPPlan { get; set; }
        public string? TitleTYPEOFFLIGHTINSPPlan { get; set; }
        public string? CategoryDescriptionTYPEOFFLIGHTINSPPlan { get; set; }
        public string? CategoryGeneralSubIdTYPEOFFLIGHTINSPPlan { get; set; }
        public string? CategoryIsActiveTYPEOFFLIGHTINSPPlan { get; set; }
        public string? CategorySortableIdTYPEOFFLIGHTINSPPlan { get; set; }
        public string? ooCategoryGeneralSubIdTYPEOFFLIGHTINSPPlan { get; set; }
        public string? SubCategoryIdTYPEOFFLIGHTINSPPlan { get; set; }
        public string? SubCategoryTitleTYPEOFFLIGHTINSPPlan { get; set; }
        public string? SubCategoryDescriptionTYPEOFFLIGHTINSPPlan { get; set; }
        public string? SubCategoryIsActiveTYPEOFFLIGHTINSPPlan { get; set; }
        public string? SubCategorySortableIdTYPEOFFLIGHTINSPPlan { get; set; }
        public string? OOSubCategoryIdTYPEOFFLIGHTINSPPlan { get; set; }
        public string? OOSubCategoryTitleTYPEOFFLIGHTINSPPlan { get; set; }
        public string? OOSubCategoryDescriptionTYPEOFFLIGHTINSPPlan { get; set; }
        public string? OOSubCategoryIsActiveTYPEOFFLIGHTINSPPlan { get; set; }
        public string? OOSubCategorySortableIdTYPEOFFLIGHTINSPPlan { get; set; }
        public string? MainSortableIdTYPEOFFLIGHTINSPPlan { get; set; }
        public string? MainSortableDescriptionTYPEOFFLIGHTINSPPlan { get; set; }
        public string? SubSortableIdTYPEOFFLIGHTINSPPlan { get; set; }
        public string? SubSortableDescriptionTYPEOFFLIGHTINSPPlan { get; set; }
        public string? WAKETURBULENCECALINSPPlan { get; set; }
        public string? TitleWAKETURBULENCECALINSPPlan { get; set; }
        public string? CategoryDescriptionWAKETURBULENCECALINSPPlan { get; set; }
        public string? CategoryGeneralSubIdWAKETURBULENCECALINSPPlan { get; set; }
        public string? CategoryIsActiveWAKETURBULENCECALINSPPlan { get; set; }
        public string? CategorySortableIdWAKETURBULENCECALINSPPlan { get; set; }
        public string? ooCategoryGeneralSubIdWAKETURBULENCECALINSPPlan { get; set; }
        public string? SubCategoryIdWAKETURBULENCECALINSPPlan { get; set; }
        public string? SubCategoryTitleWAKETURBULENCECALINSPPlan { get; set; }
        public string? SubCategoryDescriptionWAKETURBULENCECALINSPPlan { get; set; }
        public string? SubCategoryIsActiveWAKETURBULENCECALINSPPlan { get; set; }
        public string? SubCategorySortableIdWAKETURBULENCECALINSPPlan { get; set; }
        public string? OOSubCategoryIdWAKETURBULENCECALINSPPlan { get; set; }
        public string? OOSubCategoryTitleWAKETURBULENCECALINSPPlan { get; set; }
        public string? OOSubCategoryDescriptionWAKETURBULENCECALINSPPlan { get; set; }
        public string? OOSubCategoryIsActiveWAKETURBULENCECALINSPPlan { get; set; }
        public string? OOSubCategorySortableIdWAKETURBULENCECALINSPPlan { get; set; }
        public string? MainSortableIdWAKETURBULENCECALINSPPlan { get; set; }
        public string? MainSortableDescriptionWAKETURBULENCECALINSPPlan { get; set; }
        public string? SubSortableIdWAKETURBULENCECALINSPPlan { get; set; }
        public string? SubSortableDescriptionWAKETURBULENCECALINSPPlan { get; set; }
        public string? UnitID01INSPPlan { get; set; }
        public string? TitleUnitID01INSPPlan { get; set; }
        public string? CategoryDescriptionUnitID01INSPPlan { get; set; }
        public string? CategoryGeneralSubIdUnitID01INSPPlan { get; set; }
        public string? CategoryIsActiveUnitID01INSPPlan { get; set; }
        public string? CategorySortableIdUnitID01INSPPlan { get; set; }
        public string? ooCategoryGeneralSubIdUnitID01INSPPlan { get; set; }
        public string? SubCategoryIdUnitID01INSPPlan { get; set; }
        public string? SubCategoryTitleUnitID01INSPPlan { get; set; }
        public string? SubCategoryDescriptionUnitID01INSPPlan { get; set; }
        public string? SubCategoryIsActiveUnitID01INSPPlan { get; set; }
        public string? SubCategorySortableIdUnitID01INSPPlan { get; set; }
        public string? OOSubCategoryIdUnitID01INSPPlan { get; set; }
        public string? OOSubCategoryTitleUnitID01INSPPlan { get; set; }
        public string? OOSubCategoryDescriptionUnitID01INSPPlan { get; set; }
        public string? OOSubCategoryIsActiveUnitID01INSPPlan { get; set; }
        public string? OOSubCategorySortableIdUnitID01INSPPlan { get; set; }
        public string? MainSortableIdUnitID01INSPPlan { get; set; }
        public string? MainSortableDescriptionUnitID01INSPPlan { get; set; }
        public string? SubSortableIdUnitID01INSPPlan { get; set; }
        public string? SubSortableDescriptionUnitID01INSPPlan { get; set; }
        public string? INSPEDID01INSPPlan { get; set; }
        public string? ITEMTOBEINSPECTEDINSPPlan { get; set; }
        public string? REFERENCEINSPPlan { get; set; }
        public int? Sortable01IdINSPListINSPPlan { get; set; }
        public string? IsHaveJobINSPListINSPPlan { get; set; }
        public string? IsHaveJobString02INSPPlan { get; set; }
        public string? TypeHelicopterINSPListINSPPlan { get; set; }
        public string? TitleTypeHelicopterINSPListINSPPlan { get; set; }
        public int?  FREQRANGEINSPPlan { get; set; }
        public string? TitleFREQRANGEINSPPlan { get; set; }
        public string? FREQPERIODINSPPlan { get; set; }
        public string? FREQUENCY01INSPPlan { get; set; }
        public string? CategoryDescriptionFREQRANGEINSPPlan { get; set; }
        public string? CategoryGeneralSubIdFREQRANGEINSPPlan { get; set; }
        public string? CategoryIsActiveFREQRANGEINSPPlan { get; set; }
        public string? StatusConfirmation01INSPPlan { get; set; }
        public string? StatusConfirmation01strINSPPlan { get; set; }
        public string? UjobPesronel01INSPPlan { get; set; }
        public string? UjobPesronel01strINSPPlan { get; set; }
        public string? UjobPesronel01strMelicodeINSPPlan { get; set; }
        public string? UjobPesronel01strJobTitleINSPPlan { get; set; }
        public string? UjobPesronel01strJobTitleNINSPPlan { get; set; }
        public string? UjobPesronel01strDarajeeINSPPlan { get; set; }
        public string? UjobPesronel01strFirstNameINSPPlan { get; set; }
        public string? UjobPesronel01strLastNameINSPPlan { get; set; }
        public string? UjobPesronel01strEMP_NUMINSPPlan { get; set; }
        public string? StatusConfirmation02INSPPlan { get; set; }
        public string? StatusConfirmation02strINSPPlan { get; set; }
        public string? UjobPesronel02INSPPlan { get; set; }
        public string? UjobPesronel02strINSPPlan { get; set; }
        public string? UjobPesronel02strMelicodeINSPPlan { get; set; }
        public string? UjobPesronel02strJobTitleINSPPlan { get; set; }
        public string? UjobPesronel02strJobTitleNINSPPlan { get; set; }
        public string? UjobPesronel02strDarajeeINSPPlan { get; set; }
        public string? UjobPesronel02strFirstNameINSPPlan { get; set; }
        public string? UjobPesronel02strLastNameINSPPlan { get; set; }
        public string? UjobPesronel02strEMP_NUMINSPPlan { get; set; }
        public string? StatusConfirmation03INSPPlan { get; set; }
        public string? StatusConfirmation03strINSPPlan { get; set; }
        public string? UjobPesronel03INSPPlan { get; set; }
        public string? UjobPesronel03strINSPPlan { get; set; }
        public string? UjobPesronel03strMelicodeINSPPlan { get; set; }
        public string? UjobPesronel03strJobTitleINSPPlan { get; set; }
        public string? UjobPesronel03strJobTitleNINSPPlan { get; set; }
        public string? UjobPesronel03strDarajeeINSPPlan { get; set; }
        public string? UjobPesronel03strFirstNameINSPPlan { get; set; }
        public string? UjobPesronel03strLastNameINSPPlan { get; set; }
        public string? UjobPesronel03strEMP_NUMINSPPlan { get; set; }
        public string? StatusConfirmation04INSPPlan { get; set; }
        public string? StatusConfirmation04strINSPPlan { get; set; }
        public string? UjobPesronel04INSPPlan { get; set; }
        public string? UjobPesronel04strINSPPlan { get; set; }
        public string? UjobPesronel04strMelicodeINSPPlan { get; set; }
        public string? UjobPesronel04strJobTitleINSPPlan { get; set; }
        public string? UjobPesronel04strJobTitleNINSPPlan { get; set; }
        public string? UjobPesronel04strDarajeeINSPPlan { get; set; }
        public string? UjobPesronel04strFirstNameINSPPlan { get; set; }
        public string? UjobPesronel04strLastNameINSPPlan { get; set; }
        public string? UjobPesronel04strEMP_NUMINSPPlan { get; set; }
        public string? StatusConfirmation05INSPPlan { get; set; }
        public string? StatusConfirmation05strINSPPlan { get; set; }
        public string? UjobPesronel05INSPPlan { get; set; }
        public string? UjobPesronel05strINSPPlan { get; set; }
        public string? UjobPesronel05strMelicodeINSPPlan { get; set; }
        public string? UjobPesronel05strJobTitleINSPPlan { get; set; }
        public string? UjobPesronel05strJobTitleNINSPPlan { get; set; }
        public string? UjobPesronel05strDarajeeINSPPlan { get; set; }
        public string? UjobPesronel05strFirstNameINSPPlan { get; set; }
        public string? UjobPesronel05strLastNameINSPPlan { get; set; }
        public string? UjobPesronel05strEMP_NUMINSPPlan { get; set; }
        public string? StatusConfirmation06INSPPlan { get; set; }
        public string? StatusConfirmation06strINSPPlan { get; set; }
        public string? UjobPesronel06INSPPlan { get; set; }
        public string? UjobPesronel06strINSPPlan { get; set; }
        public string? UjobPesronel06strMelicodeINSPPlan { get; set; }
        public string? UjobPesronel06strJobTitleINSPPlan { get; set; }
        public string? UjobPesronel06strJobTitleNINSPPlan { get; set; }
        public string? UjobPesronel06strDarajeeINSPPlan { get; set; }
        public string? UjobPesronel06strFirstNameINSPPlan { get; set; }
        public string? UjobPesronel06strLastNameINSPPlan { get; set; }
        public string? UjobPesronel06strEMP_NUMINSPPlan { get; set; }
        public string? StatusConfirmation07INSPPlan { get; set; }
        public string? StatusConfirmation07strINSPPlan { get; set; }
        public string? UjobPesronel07INSPPlan { get; set; }
        public string? UjobPesronel07strINSPPlan { get; set; }
        public string? UjobPesronel07strMelicodeINSPPlan { get; set; }
        public string? UjobPesronel07strJobTitleINSPPlan { get; set; }
        public string? UjobPesronel07strJobTitleNINSPPlan { get; set; }
        public string? UjobPesronel07strDarajeeINSPPlan { get; set; }
        public string? UjobPesronel07strFirstNameINSPPlan { get; set; }
        public string? UjobPesronel07strLastNameINSPPlan { get; set; }
        public string? UjobPesronel07strEMP_NUMINSPPlan { get; set; }
        public string? StatusConfirmation08INSPPlan { get; set; }
        public string? StatusConfirmation08strINSPPlan { get; set; }
        public string? UjobPesronel08INSPPlan { get; set; }
        public string? UjobPesronel08strINSPPlan { get; set; }
        public string? UjobPesronel08strMelicodeINSPPlan { get; set; }
        public string? UjobPesronel08strJobTitleINSPPlan { get; set; }
        public string? UjobPesronel08strJobTitleNINSPPlan { get; set; }
        public string? UjobPesronel08strDarajeeINSPPlan { get; set; }
        public string? UjobPesronel08strFirstNameINSPPlan { get; set; }
        public string? UjobPesronel08strLastNameINSPPlan { get; set; }
        public string? UjobPesronel08strEMP_NUMINSPPlan { get; set; }
        public string? StatusConfirmation09INSPPlan { get; set; }
        public string? StatusConfirmation09strINSPPlan { get; set; }
        public string? UjobPesronel09INSPPlan { get; set; }
        public string? UjobPesronel09strINSPPlan { get; set; }
        public string? UjobPesronel09strMelicodeINSPPlan { get; set; }
        public string? UjobPesronel09strJobTitleINSPPlan { get; set; }
        public string? UjobPesronel09strJobTitleNINSPPlan { get; set; }
        public string? UjobPesronel09strDarajeeINSPPlan { get; set; }
        public string? UjobPesronel09strFirstNameINSPPlan { get; set; }
        public string? UjobPesronel09strLastNameINSPPlan { get; set; }
        public string? UjobPesronel09strEMP_NUMINSPPlan { get; set; }
        public string? StatusConfirmation10INSPPlan { get; set; }
        public string? StatusConfirmation10strINSPPlan { get; set; }
        public string? UjobPesronel10INSPPlan { get; set; }
        public string? UjobPesronel10strINSPPlan { get; set; }
        public string? UjobPesronel10strMelicodeINSPPlan { get; set; }
        public string? UjobPesronel10strJobTitleINSPPlan { get; set; }
        public string? UjobPesronel10strJobTitleNINSPPlan { get; set; }
        public string? UjobPesronel10strDarajeeINSPPlan { get; set; }
        public string? UjobPesronel10strFirstNameINSPPlan { get; set; }
        public string? UjobPesronel10strLastNameINSPPlan { get; set; }
        public string? UjobPesronel10strEMP_NUMINSPPlan { get; set; }
        public string? StatusConfirmation11INSPPlan { get; set; }
        public string? StatusConfirmation11strINSPPlan { get; set; }
        public string? UjobPesronel11INSPPlan { get; set; }
        public string? UjobPesronel11strINSPPlan { get; set; }
        public string? UjobPesronel11strMelicodeINSPPlan { get; set; }
        public string? UjobPesronel11strJobTitleINSPPlan { get; set; }
        public string? UjobPesronel11strJobTitleNINSPPlan { get; set; }
        public string? UjobPesronel11strDarajeeINSPPlan { get; set; }
        public string? UjobPesronel11strFirstNameINSPPlan { get; set; }
        public string? UjobPesronel11strLastNameINSPPlan { get; set; }
        public string? UjobPesronel11strEMP_NUMINSPPlan { get; set; }
        public string? StatusConfirmation12INSPPlan { get; set; }
        public string? StatusConfirmation12strINSPPlan { get; set; }
        public string? UjobPesronel12INSPPlan { get; set; }
        public string? UjobPesronel12strINSPPlan { get; set; }
        public string? UjobPesronel12strMelicodeINSPPlan { get; set; }
        public string? UjobPesronel12strJobTitleINSPPlan { get; set; }
        public string? UjobPesronel12strJobTitleNINSPPlan { get; set; }
        public string? UjobPesronel12strDarajeeINSPPlan { get; set; }
        public string? UjobPesronel12strFirstNameINSPPlan { get; set; }
        public string? UjobPesronel12strLastNameINSPPlan { get; set; }
        public int? StatusConfirmation01 { get; set; }
        public string? StatusConfirmation01str { get; set; }
        public string? UjobPesronel01 { get; set; }
        public string? UjobPesronel01str { get; set; }
        public string? UjobPesronel01strMelicode { get; set; }
        public string? UjobPesronel01strJobTitle { get; set; }
        public string? UjobPesronel01strJobTitleN { get; set; }
        public string? UjobPesronel01strDarajee { get; set; }
        public string? UjobPesronel01strFirstName { get; set; }
        public string? UjobPesronel01strLastName { get; set; }
        public string? UjobPesronel01strEMP_NUM { get; set; }
        public int? StatusConfirmation02 { get; set; }
        public string? StatusConfirmation02str { get; set; }
        public string? UjobPesronel02 { get; set; }
        public string? UjobPesronel02str { get; set; }
        public string? UjobPesronel02strMelicode { get; set; }
        public string? UjobPesronel02strJobTitle { get; set; }
        public string? UjobPesronel02strJobTitleN { get; set; }
        public string? UjobPesronel02strDarajee { get; set; }
        public string? UjobPesronel02strFirstName { get; set; }
        public string? UjobPesronel02strLastName { get; set; }
        public string? UjobPesronel02strEMP_NUM { get; set; }
        public int? StatusConfirmation03 { get; set; }
        public string? StatusConfirmation03str { get; set; }
        public string? UjobPesronel03 { get; set; }
        public string? UjobPesronel03str { get; set; }
        public string? UjobPesronel03strMelicode { get; set; }
        public string? UjobPesronel03strJobTitle { get; set; }
        public string? UjobPesronel03strJobTitleN { get; set; }
        public string? UjobPesronel03strDarajee { get; set; }
        public string? UjobPesronel03strFirstName { get; set; }
        public string? UjobPesronel03strLastName { get; set; }
        public string? UjobPesronel03strEMP_NUM { get; set; }
        public int? StatusConfirmation04 { get; set; }
        public string? StatusConfirmation04str { get; set; }
        public string? UjobPesronel04 { get; set; }
        public string? UjobPesronel04str { get; set; }
        public string? UjobPesronel04strMelicode { get; set; }
        public string? UjobPesronel04strJobTitle { get; set; }
        public string? UjobPesronel04strJobTitleN { get; set; }
        public string? UjobPesronel04strDarajee { get; set; }
        public string? UjobPesronel04strFirstName { get; set; }
        public string? UjobPesronel04strLastName { get; set; }
        public string? UjobPesronel04strEMP_NUM { get; set; }
        public int? StatusConfirmation05 { get; set; }
        public string? StatusConfirmation05str { get; set; }
        public string? UjobPesronel05 { get; set; }
        public string? UjobPesronel05str { get; set; }
        public string? UjobPesronel05strMelicode { get; set; }
        public string? UjobPesronel05strJobTitle { get; set; }
        public string? UjobPesronel05strJobTitleN { get; set; }
        public string? UjobPesronel05strDarajee { get; set; }
        public string? UjobPesronel05strFirstName { get; set; }
        public string? UjobPesronel05strLastName { get; set; }
        public string? UjobPesronel05strEMP_NUM { get; set; }
        public int? StatusConfirmation06 { get; set; }
        public string? StatusConfirmation06str { get; set; }
        public string? UjobPesronel06 { get; set; }
        public string? UjobPesronel06str { get; set; }
        public string? UjobPesronel06strMelicode { get; set; }
        public string? UjobPesronel06strJobTitle { get; set; }
        public string? UjobPesronel06strJobTitleN { get; set; }
        public string? UjobPesronel06strDarajee { get; set; }
        public string? UjobPesronel06strFirstName { get; set; }
        public string? UjobPesronel06strLastName { get; set; }
        public string? UjobPesronel06strEMP_NUM { get; set; }
        public int? StatusConfirmation07 { get; set; }
        public string? StatusConfirmation07str { get; set; }
        public string? UjobPesronel07 { get; set; }
        public string? UjobPesronel07str { get; set; }
        public string? UjobPesronel07strMelicode { get; set; }
        public string? UjobPesronel07strJobTitle { get; set; }
        public string? UjobPesronel07strJobTitleN { get; set; }
        public string? UjobPesronel07strDarajee { get; set; }
        public string? UjobPesronel07strFirstName { get; set; }
        public string? UjobPesronel07strLastName { get; set; }
        public string? UjobPesronel07strEMP_NUM { get; set; }
        public int? StatusConfirmation08 { get; set; }
        public string? StatusConfirmation08str { get; set; }
        public string? UjobPesronel08 { get; set; }
        public string? UjobPesronel08str { get; set; }
        public string? UjobPesronel08strMelicode { get; set; }
        public string? UjobPesronel08strJobTitle { get; set; }
        public string? UjobPesronel08strJobTitleN { get; set; }
        public string? UjobPesronel08strDarajee { get; set; }
        public string? UjobPesronel08strFirstName { get; set; }
        public string? UjobPesronel08strLastName { get; set; }
        public string? UjobPesronel08strEMP_NUM { get; set; }
        public int? StatusConfirmation09 { get; set; }
        public string? StatusConfirmation09str { get; set; }
        public string? UjobPesronel09 { get; set; }
        public string? UjobPesronel09str { get; set; }
        public string? UjobPesronel09strMelicode { get; set; }
        public string? UjobPesronel09strJobTitle { get; set; }
        public string? UjobPesronel09strJobTitleN { get; set; }
        public string? UjobPesronel09strDarajee { get; set; }
        public string? UjobPesronel09strFirstName { get; set; }
        public string? UjobPesronel09strLastName { get; set; }
        public string? UjobPesronel09strEMP_NUM { get; set; }
        public int? StatusConfirmation10 { get; set; }
        public string? StatusConfirmation10str { get; set; }
        public string? UjobPesronel10 { get; set; }
        public string? UjobPesronel10str { get; set; }
        public string? UjobPesronel10strMelicode { get; set; }
        public string? UjobPesronel10strJobTitle { get; set; }
        public string? UjobPesronel10strJobTitleN { get; set; }
        public string? UjobPesronel10strDarajee { get; set; }
        public string? UjobPesronel10strFirstName { get; set; }
        public string? UjobPesronel10strLastName { get; set; }
        public string? UjobPesronel10strEMP_NUM { get; set; }
        public int? StatusConfirmation11 { get; set; }
        public string? StatusConfirmation11str { get; set; }
        public string? UjobPesronel11 { get; set; }
        public string? UjobPesronel11str { get; set; }
        public string? UjobPesronel11strMelicode { get; set; }
        public string? UjobPesronel11strJobTitle { get; set; }
        public string? UjobPesronel11strJobTitleN { get; set; }
        public string? UjobPesronel11strDarajee { get; set; }
        public string? UjobPesronel11strFirstName { get; set; }
        public string? UjobPesronel11strLastName { get; set; }
        public string? UjobPesronel11strEMP_NUM { get; set; }
        public int? StatusConfirmation12 { get; set; }
        public string? StatusConfirmation12str { get; set; }
        public string? UjobPesronel12 { get; set; }
        public string? UjobPesronel12str { get; set; }
        public string? UjobPesronel12strMelicode { get; set; }
        public string? UjobPesronel12strJobTitle { get; set; }
        public string? UjobPesronel12strJobTitleN { get; set; }
        public string? UjobPesronel12strDarajee { get; set; }
        public string? UjobPesronel12strFirstName { get; set; }
        public string? UjobPesronel12strLastName { get; set; }
        public string? UjobPesronel12strEMP_NUM { get; set; }
    }

  


}
